name: appsicle_flutter
description: A library for displaying content from an appsicle.co site.
version: 0.0.2
homepage: https://appsicle.co/libraries/flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^2.2.1
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
